
package com.imrob.locadoraveiculos.forms;

import com.imrob.locadoraveiculos.components.CardComponent;
import com.imrob.locadoraveiculos.config.DatabaseConfig;
import com.imrob.locadoraveiculos.entities.Carro;
import com.imrob.locadoraveiculos.repositories.CarroRepository;
import com.imrob.locadoraveiculos.services.CarroService;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.List;

public class CatalogoVeiculos extends javax.swing.JPanel {
    private CardComponent card;
    public CarroService service = new CarroService(
                new CarroRepository(DatabaseConfig.jdbcClient()));
    
    public CatalogoVeiculos() {
        initComponents();
        setPreferredSize(new Dimension(800, 600));
        GridLayout gridLayout = new GridLayout(0, 4, 15, 15); // 3 colunas, 10 pixels de espaçamento horizontal e vertical
        jpConteudo.setLayout(gridLayout);

        carregarCatalogoCarros();
        
    }
    
    public void carregarCatalogoCarros() {
        List<Carro> lista = service.findAll();
        
        for (Carro c : lista) {
            jpConteudo.add(new CardComponent(c));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        jpConteudo = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout jpConteudoLayout = new javax.swing.GroupLayout(jpConteudo);
        jpConteudo.setLayout(jpConteudoLayout);
        jpConteudoLayout.setHorizontalGroup(
            jpConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jpConteudoLayout.setVerticalGroup(
            jpConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        scroll.setViewportView(jpConteudo);

        add(scroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpConteudo;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
