 /*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.imrob.locadoraveiculos;
import com.formdev.flatlaf.FlatLightLaf;
import com.imrob.locadoraveiculos.gui.TelaPrincipal;
import javax.swing.UIManager;


public class App {

    public static void main(String[] args) {
        setLookAndFeel();

        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
    }

    private static void setLookAndFeel() {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
    }
}
