
package com.imrob.locadoraveiculos.gui.gerenciar;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.imrob.locadoraveiculos.DTO.ClienteDTO;
import com.imrob.locadoraveiculos.gui.cadastro.CadastroClienteGUI;
import com.imrob.locadoraveiculos.gui.components.FormManager;
import com.imrob.locadoraveiculos.gui.editar.EditarClienteGUI;
import com.imrob.locadoraveiculos.gui.model.MappedTableModel;
import com.imrob.locadoraveiculos.services.ClienteService;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;
import javax.swing.*;
import javax.swing.table.TableRowSorter;

public class ListaClientesGUI extends javax.swing.JPanel {

    public ListaClientesGUI() {
        initComponents();
        carregarTabela();
        txtProcurar.putClientProperty(FlatClientProperties.TEXT_FIELD_TRAILING_ICON, new FlatSVGIcon(getClass().getResource("/imgs/icons/procurar.svg")));
        btnNovo.setIcon(new FlatSVGIcon(getClass().getResource("/imgs/icons/add.svg")));
        btnEditar.setIcon(new FlatSVGIcon(getClass().getResource("/imgs/icons/edit.svg")));
        btnApagar.setIcon(new FlatSVGIcon(getClass().getResource("/imgs/icons/delete.svg")));
    }
    
    public void carregarTabela() {
        MappedTableModel<ClienteDTO> tableModel = new MappedTableModel<>(
                new ClienteService().findAll(), tabela);
        tableModel.excludeColumns(new String[]{"endereco", "enderecoId"});
        tabela.setModel(tableModel);
        tableModel.setPreferredColumnWidths();
    }
    
    private void editar(){
        int linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada != -1) {
            Long id = (Long) tabela.getValueAt(linhaSelecionada, 0);
            ClienteDTO cliente = new ClienteService().findById(id);
            FormManager.getInstance().showForm("Editar Cliente", new EditarClienteGUI(cliente));

            carregarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um cliente para editar.",
                    "Nenhum cliente selecionado", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void apagar() {
        int linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada != -1) {
            Long id = (Long) tabela.getValueAt(linhaSelecionada, 0);
            ClienteDTO cliente = new ClienteService().findById(id);
            String mensagem = """
                              Tem certeza que deseja apagar esse cliente?
                              
                              Nome: %s
                              Rg: %s
                              """.formatted(cliente.getNome(), cliente.getRg());
            int resposta = JOptionPane.showConfirmDialog(this, mensagem, "Confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    new ClienteService().delete(id);
                    JOptionPane.showMessageDialog(null, "O cliente selecionado foi apagado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Não foi possivel excluir o cliente. Erro: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
            carregarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um cliente para apagar.",
                    "Nenhuma cliente selecionado", JOptionPane.WARNING_MESSAGE);
        }
            
    }
    
    private void atualizarFiltro() {
        MappedTableModel<ClienteDTO> tableModel = new MappedTableModel<>(new ClienteService().findAll());
        TableRowSorter<MappedTableModel<ClienteDTO>> sorter = new TableRowSorter<>(tableModel);
        tabela.setRowSorter(sorter);
        String texto = txtProcurar.getText();
        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + Pattern.quote(texto)));
            } catch (PatternSyntaxException e) {
                sorter.setRowFilter(null);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crazyPanel2 = new raven.crazypanel.CrazyPanel();
        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        txtProcurar = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(700, 610));

        crazyPanel2.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap,fill,insets 15",
            "[fill]",
            "[grow 0][fill]",
            null
        ));

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "",
            new String[]{
                "JTextField.placeholderText=Procurar;background:#1D272A",
                "background:lighten(#1D272A,8%);borderWidth:1",
                "background:lighten(#1D272A,8%);borderWidth:1",
                "background:lighten(#1D272A,8%);borderWidth:1",
                ""
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "",
            "[]push[][]",
            "",
            new String[]{
                "width 200"
            }
        ));

        txtProcurar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProcurarKeyTyped(evt);
            }
        });
        crazyPanel1.add(txtProcurar);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        crazyPanel1.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        crazyPanel1.add(btnEditar);

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(this::btnApagarActionPerformed);
        crazyPanel1.add(btnApagar);

        crazyPanel2.add(crazyPanel1);

        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        crazyPanel2.add(jScrollPane1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(crazyPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(crazyPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        FormManager.getInstance().showForm("Cadastro de Cliente", new CadastroClienteGUI());
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
       apagar();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked

    }//GEN-LAST:event_tabelaMouseClicked

    private void txtProcurarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProcurarKeyTyped
        atualizarFiltro();
    }//GEN-LAST:event_txtProcurarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private raven.crazypanel.CrazyPanel crazyPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables
}
